# This file should be renamed to docker-compose.yaml
# in order to test and compile english version
version: '3'
services:
  mkdocs:
    build: . 
    container_name: mkdocs
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app
    working_dir: /app/en
