# This is the spanish version of the docs
version: '3'
services:
  mkdocs:
    build: . 
    container_name: mkdocs
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app
    working_dir: /app/en
